- type: latheRecipePack
  id: ADTMechEquipmentSecTechfabPack
  recipes:
  # - MechEquipmentArmorMelee Вырезано из-за неработоспособности
  # - MechEquipmentArmorRange Вырезано из-за неработоспособности
  - ADTMechGunImmolatorLaser
  - ADTMechGunPeacemakerDisabler
  - ADTMechGunSolarisLaserCannon
  - ADTMechGunTeslaCannon
  - ADTMechGunScattershot
  - ADTMechGunUltraAC2
  - ADTMechGunFNX99Hades
  # - ADTMechGunMHAR21       Вырезано ради баланса
  - ADTMechGunSGL6
  - ADTMechGunBRM6
  # - ADTMechGunSRM8         Вырезано ради баланса
  - ADTBoxAmmoAC2Ultra
  - ADTBoxAmmoScattershot
  - ADTBoxAmmoHades
  # - ADTBoxAmmoSniper       Вырезано ради баланса
  - ADTBoxAmmoGranade
